create table if not exists public.pending_registrations (
  id bigint generated by default as identity primary key,
  email text not null unique,
  encrypted_password text not null,
  token_hash text not null unique,
  full_name text not null default '',
  matric_number text,
  phone text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.pending_registrations enable row level security;

create index if not exists pending_registrations_expires_at_idx
  on public.pending_registrations (expires_at);
